package in.vedchangani.billingsoftware.io;

public enum AuditAction {
    AUTH_LOGIN_SUCCESS,
    ACCOUNT_REGISTERED,

    PROFILE_UPDATED,
    PASSWORD_CHANGED,

    CASHIER_CREATED,
    CASHIER_DEACTIVATED,
    CASHIER_REACTIVATED,
    CASHIER_PASSWORD_RESET,

    ONLINE_ORDER_CREATED,
    POS_ORDER_CREATED,
    PAYMENT_VERIFIED,
    PAYMENT_FAILED,
    ORDER_CANCELLED,
    ORDER_DELETED,

    ITEM_CREATED,
    ITEM_UPDATED,
    ITEM_DELETED,
    INVENTORY_ADJUSTED,

    CATEGORY_CREATED,
    CATEGORY_DELETED
}
